# Generated by Django 2.2.1 on 2019-06-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil Bilgileri'},
        ),
    ]
